version: '3'
services:
  php-apache:
    build: .
    container_name: templomi-php-apache
    volumes:
      - ./forraskod/:/var/www/html/
      - /var/www/html/vendor/
    ports:
      - 80:80
    links:
      - db
  db:
    image: mysql
    container_name: templomi-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: templomigithub
    ports:
      - 3306:3306
  phpmyadmin:
    image: phpmyadmin
    ports:
      - 8080:80
    depends_on:
      - php-apache
      - db
    links:
      - db
